package response

type AuthorizationCodeGrantResponse struct {
	Code  string `json:"code"`  // The authorization code generated by the authorization server.
	State string `json:"state"` // The exact value received from the client.
}
